[workspace]
members = [
    "crates/owlrora-cli",
    "crates/owlrora-key-provider",
    "crates/owlrora-server",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "BSD-3-Clause"
repository = "https://github.com/owlfoundry/owlrora"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[profile.dev]
debug = "line-tables-only"
incremental = false

[profile.test]
debug = "line-tables-only"
incremental = false
